#!/bin/bash
# Copyright 2022-2023 Dan Moulding
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <https://www.gnu.org/licenses/>.

function add_mod()
{
    local mod=${1}

    if ! mod_added "${mod}" "${mods[@]}"; then
        mods+=("${mod}")
    fi
}

function blockdev_type()
{
    local dev=${1}

    lsblk --nodeps --noheadings --output TYPE "${dev}"
}

function mod_added()
{
    local mod=${1}
    local other_mod

    for other_mod in "${mods[@]}"; do
        if [[ "${mod}" == "${other_mod}" ]]; then
            return 0
        fi
    done
    return 1
}

function on_exit()
{
    if [[ -n "${config}" ]]; then
        rm -f "${config}"
    fi
    if [[ -n "${gi_log}" ]]; then
        rm -f "${gi_log}"
    fi
    if [[ -n "${gbs_log}" ]]; then
        rm -f "${gbs_log}"
    fi
    for ((i = ${#mounted[@]} - 1; i >= 0; --i)); do
        umount "${mounted[i]}"
    done
}

firmware=

trap on_exit EXIT

if [[ "${EUID}" != 0 ]]; then
    echo "Only root can run this script. (Did you forget to use \"sudo\"?)" >&2
    exit 1
fi

if [[ "$(uname -m)" != x86_64 ]]; then
    echo "This script is designed to install GRUB on x86_64 systems only." >&2
    exit 1
fi

if [[ -d /sys/firmware/efi ]]; then
    firmware=uefi
else
    firmware=bios
    boot_disk=${1}
    if [[ -z "${boot_disk}" ]]; then
        echo "This system uses BIOS firmware. Please specify the boot disk." >&2
        echo "The boot disk is the disk the BIOS will load the master boot" >&2
        echo "record from. This is often, but not always, the same disk" >&2
        echo "that contains the volume containing /boot." >&2
        exit 1
    fi
    if [[ ! -b "${boot_disk}" ]]; then
        echo "${boot_disk} is not a valid block device." >&2
        exit 1
    fi
    if [[ "$(blockdev_type "${boot_disk}")" != disk ]]; then
        echo "${boot_disk} does not appear to be a regular disk device." >&2
        read -p "Continue? : "
        if [[ "${REPLY}" != y ]]; then
            exit 1
        fi
    fi
fi

if mountpoint /boot &> /dev/null; then
    bootmnt=/boot
else
    if mount /boot &> /dev/null; then
        bootmnt=/boot
        mounted+=(/boot)
    else
        echo "Nothing mounts at /boot. If this is correct, and /boot is" >&2
        echo "supposed to be on the same device as the root file system," >&2
        echo "then enter 'y' to continue." >&2
        read -p "Continue? : "
        if [[ "${REPLY}" != y ]]; then
            exit 1
        fi
        bootmnt=/
    fi
fi

if [[ "${firmware}" == uefi ]]; then
    if ! mountpoint /boot/efi &> /dev/null; then
        if mount /boot/efi; then
            mounted+=(/boot/efi)
        else
            echo "Nothing mounts at /boot/efi. This must be a misconfiguration" >&2
            echo "(unless your entire root file system is on the EFI system" >&2
            echo "partition [ESP] which would be highly unusual). The ESP" >&2
            echo "must be mounted or the core image cannot be installed." >&2
            exit 1
        fi
    fi
fi

bootdev=$(awk -v bootmnt="${bootmnt}" \
          '$2 == bootmnt && $1 ~ /^\/dev/ { print $1; exit }' \
          /proc/self/mounts)
if [[ -z "${bootdev}" ]]; then
    echo "Failed to determine which device is the boot device." >&2
    echo "The boot device is the volume containing /boot." >&2
    read -p "Enter the name of the boot device (e.g. /dev/sda1): "
    bootdev=${REPLY}
    if [[ ! -b "${bootdev}" ]]; then
        echo "${bootdev} is not a valid block device name." >&2
        exit 1
    fi
fi

devtype=$(lsblk --noheadings --output TYPE "${bootdev}")
case "${devtype}" in
    crypt)
        root=crypt0
        ;;
    lvm)
        output=$(lvdisplay "${bootdev}")
        vgname=$(awk '/VG Name/ { print $NF; exit }' <<< "${output}")
        lvname=$(awk '/LV Name/ { print $NF; exit }' <<< "${output}")
        root=lvm/${vgname}-${lvname}
        ;;
    part)
        partnum=$(grep -Eo '[[:digit:]]+$' <<< "${bootdev}")
        root=crypt0,${partnum}
        ;;
esac
if [[ "${bootmnt}" == /boot ]]; then
    prefix=(${root})/grub
else
    prefix=(${root})/boot/grub
fi

output=$(lsblk --inverse --list --noheadings --output NAME,TYPE --paths \
         "${bootdev}")
luksdev=$(awk '$2 == "crypt" { crypt = 1; next } crypt { print $1; exit }' \
          <<< "${output}")
if [[ -z "${luksdev}" ]] || ! cryptsetup isLuks "${luksdev}"; then
    echo "Failed to find LUKS device containing ${bootdev}." >&2
    exit 1
fi

output=$(cryptsetup luksDump "${luksdev}")
uuid=$(awk '$1 == "UUID:" { print $2; exit }' <<< "${output}")
cipher=$(awk '$1 == "Cipher:" { print $2; exit }' <<< "${output}")
hash=$(awk '$1 == "Hash:" { print $2; exit }' <<< "${output}")
pbkdf=$(awk '$1 == "PBKDF:" { print $2; exit }' <<< "${output}")

echo "Firmware        : ${firmware^^}"
if [[ "${firmware}" == bios ]]; then
    echo "Boot disk       : ${boot_disk}"
fi
echo "Boot mountpoint : ${bootmnt}"
echo "Boot device     : ${bootdev}"
echo "Boot device type: ${devtype}"
echo "LUKS device     : ${luksdev}"
echo "LUKS device UUID: ${uuid}"
echo "LUKS cipher     : ${cipher}"
echo "LUKS hash       : ${hash}"
echo "LUKS PBKDF      : ${pbkdf}"
echo "GRUB root       : ${root}"
echo "GRUB prefix     : ${prefix}"
echo ""
read -p "Enter 'y' if the above looks correct: "
if [[ "${REPLY}" != y ]]; then
    exit 1
fi
echo ""

if [[ "${pbkdf}" != pbkdf2 ]]; then
    echo "GRUB (as of 2.06) only supports pbkdf2. GRUB will not be able to" >&2
    echo "unlock your boot volume which is using ${pbkdf}. Please change" >&2
    echo "the PBKDF algorithm on ${luksdev} to pbkdf2 before installing GRUB." >&2
    exit 1
fi

# grub-install needs to be run to copy the modules and other files
# (fonts, locales, themes, etc.) to the boot volume. On UEFI it also
# will create the required directory structure on the EFI system
# partition and set the EFI NVRAM variables via efibootmgr. We also
# run it in verbose mode and then glean from the log which modules it
# would have included (which won't include any of the LUKS modules),
# so that we know what modules in addition to the LUKS modules we
# should include.
if ! gi_log=$(mktemp grub-install.log.XXXX); then
    exit 1
fi
echo -n "Running grub-install... "
args=(--verbose)
if [[ "${firmware}" == bios ]]; then
    args+=("${boot_disk}")
fi
if ! grub-install "${args[@]}" &> "${gi_log}"; then
    echo "FAILED."
    echo ""
    mv "${gi_log}" grub-install.log
    chmod a+r grub-install.log
    echo "grub-install failed. Check grub-install.log for reason." >&2
    exit 1
fi
echo "done."

if [[ "${firmware}" == bios ]]; then
    boot_image=/boot/grub/i386-pc/boot.img
    if [[ ! -f "${boot_image}" ]]; then
        echo "grub-install succeeded, but ${boot_image} is missing." >&2
        exit 1
    fi
fi

mods=($(grep -o 'reading.*[.]mod' "${gi_log}" | sort -u |
        awk '{ gsub(/.*\/|[.]mod/, "", $2); print $2 }'))

# grub-install will have failed to detect anything beyond the LUKS
# container (so it won't detect if there's a GPT partition backing the
# LUKS container, for example). We'll walk the "device stack" from the
# LUKS device on down and see if any other GRUB modules will be needed
# to handle those devices.
devstack=($(lsblk --inverse --list --noheadings --output NAME,TYPE --paths \
            "${luksdev}"))
for index in "${!devstack[@]}"; do
    if ((index % 2 == 0)); then
        dev=${devstack[index]}
        continue
    else
        type=${devstack[index]}
    fi
    case "${type}" in
        crypt)
            # crypt modules are always added, the selection of which
            # is handled below.
            :
            ;;
        disk)
            # No GRUB module needed for disks.
            :
            ;;
        lvm)
            add_mod lvm
            ;;
        part)
            parttype=$(blkid -p -s PART_ENTRY_SCHEME -o value "${dev}")
            case "${parttype}" in
                dos)
                    add_mod part_msdos
                    ;;
                gpt)
                    add_mod part_gpt
                    ;;
                *)
                    echo "Unhandled partition type: ${parttype}" >&2
                    exit 1
                    ;;
            esac
            ;;
        raid*)
            output=$(mdadm --detail "${dev}")
            if [[ "${?}" -ne 0 ]]; then
                echo "Failed to get RAID details for ${dev}" >&2
                exit 1
            fi
            raid_version=$(awk '/Version/ { print $NF; exit }' <<< "${output}")
            raid_level=$(awk '/Raid Level/ { print $NF; exit }' <<< "${output}")
            case "${raid_version}" in
                1.*)
                    add_mod mdraid1x
                    ;;
                0.9*)
                    add_mod mdraid09
                    ;;
                *)
                    echo "Unhandled MD-RAID version: ${raid_version}" >&2
                    exit1
            esac
            # GRUB only has raid5 and raid6 modules. Presumably the
            # other common levels (i.e. raid0 and raid1) are handled
            # by mdraid1x/mdraid09.
            case "${raid_level}" in
                raid5)
                    add_mod raid5rec
                    ;;
                raid6)
                    add_mod raid6rec
                    ;;
            esac
            ;;
        *)
            echo "Unhandled device type: ${type} (${dev})" >&2
            exit 1
            ;;
    esac
done

# cryptodisk and luks2 will always be required.
add_mod cryptodisk
add_mod luks2

# Add the required cipher module.
case "${cipher}" in
    aes*)       add_mod gcry_rijndael;;
    blowfish*)  add_mod gcry_blowfish;;
    camellia*)  add_mod gcry_camellia;;
    cast5*)     add_mod gcry_cast5;;
    des*|3des*) add_mod gcry_des;;
    serpent*)   add_mod gcry_serpent;;
    twofish*)   add_mod gcry_twofish;;
    *)
        # Can add additional future ciphers as support for them is
        # added to GRUB/LUKS2.
        echo "Unhandled cipher type: ${cipher}" >&2
        exit 1
        ;;
esac

# Add the required hash module.
case "${hash}" in
    crc*)      add_mod gcry_crc;; # really??
    md4)       add_mod gcry_md4;;
    md5)       add_mod gcry_md5;;
    ripemd160) add_mod gcry_rmd160;;
    sha1)      add_mod gcry_sha1;;
    sha256)    add_mod gcry_sha256;;
    sha512)    add_mod gcry_sha512;;
    whirlpool) add_mod gcry_whirlpool;;
    *)
        # Can add additional future hashes as support for them is
        # added to GRUB/LUKS2.
        echo "Unhandled hash type: ${hash}" >&2
        exit 1
        ;;
esac

# Add the required PBKDF module.
case "${pbkdf}" in
    pbkdf2) add_mod pbkdf2;;
    *)
        # Can add additional future PBKDFs as support for them is
        # added to GRUB.
        echo "Unhandled PBKDF type: ${pbkdf}" >&2
        exit 1
        ;;
esac

if [[ "${firmware}" == uefi ]]; then
    # We can also glean from the log where grub-install wants the core
    # image to be output.
    image=$(awk '/copying.*\/boot\/grub\/x86_64-efi\/core.efi/ {
        gsub(/[`'"'"']|[.]$/, "", $NF); print $NF; exit }' "${gi_log}")

    echo "Core image is ${image}"
else
    image=/boot/grub/i386-pc/core.img
fi

# GRUB will load the "normal" module after executing any embedded
# configuration, so the only thing we need to do in our embedded
# configuration is cryptomount the LUKS device containing the boot
# volume.
config=$(mktemp grub.cfg.XXXX)
echo "cryptomount -u ${uuid//-/}" > "${config}"

case "${firmware}" in
    bios) format=i386-pc;;
    uefi) format=x86_64-efi;;
    *)
        echo "Unhandled firmware type: ${firmware}"
        exit 1
        ;;
esac

opts=(-c "${config}")
opts+=(-o "${image}")
opts+=(-O "${format}")
opts+=(-p "${prefix}")

output=$(grub-mkimage "${opts[@]}" "${mods[@]}" 2>&1)
if [[ "${?}" -ne 0 ]]; then
    echo "grub-mkimage failed: ${output}" >&2
    exit 1
fi
echo "Wrote new core image with the following modules:"
echo "${mods[*]}"

if [[ "${firmware}" == bios ]]; then
    if ! gbs_log=$(mktemp grub-bios-setup.log.XXXX); then
        exit 1
    fi
    echo -n "Installing core image to ${boot_disk}... "
    opts=(--boot-image="${boot_image#/boot/grub}")
    opts+=(--core-image="${image#/boot/grub}")
    if ! grub-bios-setup "${opts[@]}" "${boot_disk}" &> "${gbs_log}"
    then
        echo "FAILED."
        echo ""
        mv "${gbs_log}" grub-bios-setup.log
        chmod a+r grub-bios-setup.log
        echo "grub-bios-setup failed. Check grub-bios-setup.log for reason." >&2
        exit 1
    fi
    echo "done."
fi

exit 0

# Local Variables:
# sh-basic-offset: 4
# indent-tabs-mode: nil
# End:
